### PR TITLE
feat: add eslint configuration files and plugins

### PR DESCRIPTION
**Pull request by alvarogfn**
# Description

This pull request adds eslint configuration file and plugins to the project to enforce consistent code style and quality. I also added some popular plugins, such as `eslint-plugin-jsx-a11y`, `eslint-plugin-simple-import-sort`, and `eslint-plugin-unused-imports`, to enforce best practices for acessibility and to help code review.

# Motivation

The project currently does not have any linting or formatting tools, which makes it hard to maintain code quality and readability across different contributors and editors.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Code Style (formatting, missing semi colons, etc; no code change)

I would appreciate any feedback on the eslint rules and settings that I added. Do they match your expectations and preferences? Are there any rules that you would like to add or remove?

### CODE REVIEW

**Review by lincolixavier — CHANGES_REQUESTED** [review]
I'm not gonna use cypress anymore and I prefer simple quotes

**Comment by alvarogfn** [comment]
@lincolixavier okay, i will fix it.

Do you intend to keep the project in pure Javascript?

**Comment by lincolixavier** [comment]
Nope, im planning to use TS @alvarogfn

**Comment by alvarogfn** [comment]
@lincolixavier done ;)

**Review by lincolixavier — APPROVED** [review]

**Pull request closed without merging**
